import { useEffect, useState, type ReactNode } from 'react'
import { Link, NavLink, Navigate, Route, Routes, useLocation } from 'react-router-dom'
import { ArrowRight, BarChart3, ChevronRight, ClipboardList, ExternalLink, GraduationCap, Laptop, LibraryBig, Mail, MapPin, Menu, Phone, Search, ShieldCheck, Sparkles, WalletCards, X } from 'lucide-react'
import { faculties, newsItems, officialProgramPages, serviceItems } from './data'

const primaryNavigation = [
  { label: 'Home', to: '/' }, { label: 'Faculties', to: '/faculties' },
  { label: 'Programs', to: '/programs' }, { label: 'News', to: '/news' },
  { label: 'Admissions', to: '/admissions' }, { label: 'Student services', to: '/student-services' },
]
const iconMap = { clipboard: ClipboardList, laptop: Laptop, mail: Mail, library: LibraryBig, chart: BarChart3, wallet: WalletCards }

function AppShell({ children }: { children: ReactNode }) {
  const [open, setOpen] = useState(false)
  const location = useLocation()
  useEffect(() => { window.scrollTo({ top: 0, behavior: 'instant' }) }, [location.pathname])
  return <div className="min-h-screen bg-stone-50 text-slate-900">
    <div className="bg-amber-300 px-4 py-2.5 text-center text-xs font-bold leading-5 text-amber-950 sm:text-sm">Unofficial concept mockup · Not an official North Bangkok University website · Verify all decisions at <a className="underline underline-offset-2" href="https://northbkk.ac.th/" target="_blank" rel="noreferrer">northbkk.ac.th</a></div>
    <header className="sticky top-0 z-50 border-b border-white/10 bg-emerald-950/95 text-white backdrop-blur-xl">
      <div className="page-width flex h-20 items-center justify-between gap-6">
        <Link to="/" className="flex items-center gap-3" aria-label="NBU concept home"><span className="grid size-11 place-items-center rounded-full border border-amber-300/60 bg-amber-300 text-emerald-950"><GraduationCap size={23} strokeWidth={2.2} /></span><span><span className="block text-[10px] font-bold uppercase tracking-[0.23em] text-emerald-200">North Bangkok</span><span className="font-display text-xl font-semibold">University</span></span></Link>
        <nav className="hidden items-center gap-1 lg:flex" aria-label="Primary navigation">{primaryNavigation.map((item) => <NavLink key={item.to} to={item.to} className={({ isActive }) => `rounded-full px-3.5 py-2 text-sm font-medium transition ${isActive ? 'bg-white text-emerald-950' : 'text-emerald-50 hover:bg-white/10'}`}>{item.label}</NavLink>)}</nav>
        <div className="hidden items-center gap-2 lg:flex"><Link to="/programs" className="icon-button" aria-label="Search programs"><Search size={18} /></Link><Link to="/admissions" className="rounded-full bg-amber-300 px-5 py-2.5 text-sm font-bold text-emerald-950 transition hover:bg-amber-200">Start here</Link></div>
        <button className="icon-button lg:hidden" onClick={() => setOpen((value) => !value)} aria-label={open ? 'Close menu' : 'Open menu'} aria-expanded={open}>{open ? <X /> : <Menu />}</button>
      </div>
      {open && <nav className="border-t border-white/10 px-5 py-5 lg:hidden" aria-label="Mobile navigation"><div className="grid gap-1">{primaryNavigation.map((item) => <NavLink key={item.to} to={item.to} onClick={() => setOpen(false)} className={({ isActive }) => `rounded-xl px-4 py-3 font-semibold ${isActive ? 'bg-white text-emerald-950' : 'text-white hover:bg-white/10'}`}>{item.label}</NavLink>)}</div></nav>}
    </header>{children}<Footer />
  </div>
}

function VerifiedTag({ mock = false }: { mock?: boolean }) { return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-widest ${mock ? 'bg-slate-100 text-slate-600' : 'bg-emerald-100 text-emerald-800'}`}><ShieldCheck size={12} />{mock ? 'Mock summary' : 'Source verified'}</span> }
function SectionHeading({ eyebrow, title, body, action }: { eyebrow: string; title: string; body?: string; action?: ReactNode }) { return <div className="mb-10 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div className="max-w-2xl"><p className="eyebrow">{eyebrow}</p><h2 className="section-title">{title}</h2>{body && <p className="mt-4 max-w-xl text-base leading-7 text-slate-600">{body}</p>}</div>{action}</div> }
function PageHero({ eyebrow, title, body }: { eyebrow: string; title: string; body: string }) { return <section className="relative overflow-hidden bg-emerald-950 py-20 text-white sm:py-28"><div className="absolute -right-28 -top-32 size-[28rem] rounded-full border-[70px] border-emerald-800/70" /><div className="absolute bottom-8 right-[22%] size-24 rotate-12 rounded-3xl bg-amber-300/90" /><div className="page-width relative"><p className="mb-5 text-xs font-bold uppercase tracking-[0.25em] text-amber-300">{eyebrow}</p><h1 className="max-w-4xl font-display text-5xl font-semibold leading-[1.02] sm:text-7xl">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-emerald-100">{body}</p></div></section> }

function HomePage() { return <main>
  <section className="relative overflow-hidden bg-emerald-950 pb-20 pt-12 text-white sm:pb-28 sm:pt-20"><div className="hero-grid page-width relative grid items-center gap-12 lg:grid-cols-[1.08fr_.92fr]"><div className="relative z-10"><VerifiedTag mock /><h1 className="mt-7 max-w-3xl font-display text-5xl font-semibold leading-[.98] sm:text-7xl xl:text-[5.4rem]">Learn boldly.<br /><span className="text-amber-300">Build what’s next.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-emerald-100">A refreshed, student-first concept for exploring North Bangkok University’s verified study areas and public services.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link className="primary-button" to="/programs">Explore programs <ArrowRight size={18} /></Link><Link className="secondary-button" to="/admissions">Admissions overview</Link></div></div><div className="relative mx-auto aspect-[4/4.5] w-full max-w-[530px]"><div className="absolute inset-[8%] rotate-3 rounded-[3.5rem] bg-gradient-to-br from-amber-300 via-orange-300 to-rose-400" /><div className="absolute inset-x-[16%] bottom-[8%] top-[2%] -rotate-3 overflow-hidden rounded-[3rem] border border-white/20 bg-emerald-800 p-7 shadow-2xl"><div className="flex items-center justify-between text-xs font-bold uppercase tracking-widest text-emerald-200"><span>Future-facing</span><Sparkles size={20} className="text-amber-300" /></div><div className="mt-16 space-y-4 sm:mt-24"><div className="rounded-3xl bg-white p-5 text-emerald-950"><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">9 verified destinations</p><p className="mt-2 font-display text-3xl font-semibold">Find your faculty</p></div><div className="ml-10 rounded-3xl bg-amber-300 p-5 text-emerald-950"><p className="font-bold">Bachelor’s · Graduate · Short courses</p><p className="mt-1 text-sm">Official study pathway pages</p></div></div></div></div></div></section>
  <section className="border-b border-slate-200 bg-white py-6"><div className="page-width flex flex-wrap items-center justify-center gap-x-10 gap-y-3 text-sm font-semibold text-slate-600"><span className="text-xs uppercase tracking-[.2em] text-slate-400">Study pathways</span><a href={officialProgramPages.bachelors} target="_blank" rel="noreferrer">Bachelor’s ↗</a><a href={officialProgramPages.graduate} target="_blank" rel="noreferrer">Graduate ↗</a><a href={officialProgramPages.shortCourses} target="_blank" rel="noreferrer">Short courses ↗</a><Link to="/admissions">Scholarships →</Link></div></section>
  <section className="page-width py-20 sm:py-28"><SectionHeading eyebrow="Find your direction" title="Nine places to begin" body="Faculty and college names are verified from their public destinations. Descriptions are original mockup summaries." action={<Link className="text-link" to="/faculties">View all faculties <ArrowRight size={17} /></Link>} /><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{faculties.slice(0, 6).map((faculty, index) => <FacultyCard key={faculty.slug} faculty={faculty} index={index} />)}</div></section>
  <section className="bg-slate-900 py-20 text-white sm:py-28"><div className="page-width"><SectionHeading eyebrow="One useful starting point" title="Student services, made easier to scan" body="These cards hand off to verified public or account-based university systems. This concept does not implement or imitate authenticated tools." /><div className="grid gap-px overflow-hidden rounded-[2rem] bg-white/10 sm:grid-cols-2 lg:grid-cols-3">{serviceItems.map((service) => <ServiceCard key={service.name} service={service} dark />)}</div></div></section>
  <section className="page-width py-20 sm:py-28"><SectionHeading eyebrow="Official notices" title="What’s happening" body="Date-sensitive items are summaries of public listings. Always check the official source before acting." action={<Link className="text-link" to="/news">See all notices <ArrowRight size={17} /></Link>} /><div className="grid gap-5 lg:grid-cols-3">{newsItems.map((item) => <NewsCard key={item.title} item={item} />)}</div></section><Callout />
</main> }

function FacultyCard({ faculty, index }: { faculty: (typeof faculties)[number]; index: number }) { return <article className="group overflow-hidden rounded-[1.75rem] border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className={`h-2 bg-gradient-to-r ${faculty.accent}`} /><div className="p-6 sm:p-7"><div className="flex items-start justify-between gap-4"><span className="font-display text-4xl text-slate-200">{String(index + 1).padStart(2, '0')}</span><VerifiedTag /></div><p className="mt-7 text-xs font-bold uppercase tracking-[.2em] text-emerald-700">{faculty.eyebrow}</p><h3 className="mt-2 font-display text-2xl font-semibold leading-tight text-slate-900">{faculty.name}</h3><p className="mt-4 leading-6 text-slate-600">{faculty.description}</p><a href={faculty.source} target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-emerald-800">Official faculty site <ExternalLink size={15} /></a></div></article> }
function NewsCard({ item }: { item: (typeof newsItems)[number] }) { return <article className="flex min-h-72 flex-col rounded-[1.75rem] border border-slate-200 bg-white p-6 shadow-sm sm:p-7"><div className="flex items-center justify-between gap-3"><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-900">{item.category}</span><VerifiedTag /></div><p className="mt-7 text-xs font-bold uppercase tracking-widest text-slate-400">{item.dateLabel}</p><h3 className="mt-2 font-display text-2xl font-semibold leading-tight">{item.title}</h3><p className="mt-4 text-sm leading-6 text-slate-600">{item.description}</p><a className="mt-auto pt-6 text-link" href={item.source} target="_blank" rel="noreferrer">Check official source <ExternalLink size={15} /></a></article> }
function ServiceCard({ service, dark = false }: { service: (typeof serviceItems)[number]; dark?: boolean }) { const Icon = iconMap[service.icon as keyof typeof iconMap]; return <a href={service.href} target="_blank" rel="noreferrer" className={`group p-7 transition sm:p-8 ${dark ? 'bg-slate-900 hover:bg-emerald-900' : 'rounded-[1.5rem] border border-slate-200 bg-white hover:border-emerald-700'}`}><span className={`grid size-12 place-items-center rounded-2xl ${dark ? 'bg-white/10 text-amber-300' : 'bg-emerald-100 text-emerald-800'}`}><Icon size={23} /></span><div className="mt-8 flex items-center justify-between gap-3"><h3 className="font-display text-2xl font-semibold">{service.name}</h3><ExternalLink size={17} className="opacity-50 transition group-hover:opacity-100" /></div><p className={`mt-3 text-sm leading-6 ${dark ? 'text-slate-300' : 'text-slate-600'}`}>{service.description}</p></a> }

function FacultiesPage() { return <main><PageHero eyebrow="Faculties & colleges" title="Choose the questions you want to answer." body="Browse nine verified academic destinations, then continue to each official faculty site for current details." /><section className="page-width py-20 sm:py-28"><div className="mb-10 flex flex-wrap items-center justify-between gap-4"><p className="max-w-2xl text-slate-600">Program examples below were visible on faculty public pages when researched. Names and availability can change.</p><VerifiedTag /></div><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{faculties.map((faculty, index) => <FacultyCard key={faculty.slug} faculty={faculty} index={index} />)}</div></section><Callout /></main> }
function ProgramsPage() { const levels = [{ label: 'Bachelor’s', body: 'Explore the official undergraduate faculty listing.', href: officialProgramPages.bachelors, number: '01' }, { label: 'Graduate', body: 'Find master’s, doctoral, and graduate-certificate pathways.', href: officialProgramPages.graduate, number: '02' }, { label: 'Short courses', body: 'The public page includes elderly-care training and tour-guide course links.', href: officialProgramPages.shortCourses, number: '03' }]; return <main><PageHero eyebrow="Program finder" title="Start broad. Then go deeper." body="This concept groups verified public program information by study level and faculty. Tuition, duration, intake, and eligibility are intentionally not inferred." /><section className="page-width py-20 sm:py-28"><SectionHeading eyebrow="Study level" title="Three ways into the catalogue" body="Each destination opens an official public NBU page." /><div className="grid gap-5 lg:grid-cols-3">{levels.map((level) => <a key={level.label} href={level.href} target="_blank" rel="noreferrer" className="group rounded-[2rem] bg-emerald-900 p-8 text-white transition hover:-translate-y-1 hover:bg-emerald-800"><span className="font-display text-5xl text-emerald-600">{level.number}</span><h3 className="mt-12 font-display text-3xl font-semibold">{level.label}</h3><p className="mt-3 min-h-12 text-emerald-100">{level.body}</p><span className="mt-8 inline-flex items-center gap-2 font-bold text-amber-300">Open official listing <ExternalLink size={16} /></span></a>)}</div></section><section className="bg-white py-20"><div className="page-width"><SectionHeading eyebrow="Verified examples" title="Program fields by faculty" body="A selective index—not a complete or current admissions catalogue." /><div className="grid gap-4 md:grid-cols-2">{faculties.map((faculty) => <div key={faculty.slug} className="rounded-3xl border border-slate-200 p-6"><div className="flex justify-between gap-4"><h3 className="font-display text-xl font-semibold">{faculty.name}</h3><a href={faculty.source} target="_blank" rel="noreferrer" aria-label={`Open ${faculty.name} official site`}><ExternalLink size={17} /></a></div><div className="mt-5 flex flex-wrap gap-2">{faculty.programs.map((program) => <span key={program} className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-700">{program}</span>)}</div></div>)}</div></div></section><Callout /></main> }
function NewsPage() { return <main><PageHero eyebrow="News & notices" title="A clearer view of time-sensitive updates." body="These concise cards reference public university listings. Dates use the source’s Buddhist Era notation; always confirm instructions on the official page." /><section className="page-width py-20 sm:py-28"><div className="mb-8 rounded-2xl border border-amber-300 bg-amber-50 p-5 text-sm leading-6 text-amber-950"><strong>Important:</strong> This static concept does not provide live updates. Every action-sensitive card links to its official source.</div><div className="grid gap-5 lg:grid-cols-3">{newsItems.map((item) => <NewsCard key={item.title} item={item} />)}</div></section></main> }
function AdmissionsPage() { return <main><PageHero eyebrow="Admissions concept" title="Your next step should feel possible." body="A simple orientation to verified public entry points—without inventing application links, requirements, tuition, or deadlines." /><section className="page-width py-20 sm:py-28"><SectionHeading eyebrow="Plan your path" title="Explore before you apply" body="These pathway links are verified. Register-interest and scholarship labels are public, but stable deep links were not available in the approved research." /><div className="grid gap-5 md:grid-cols-3"><StepCard number="01" title="Choose a level" body="Compare the bachelor’s, graduate, and short-course entry points." link="/programs" /><StepCard number="02" title="Find your faculty" body="Review selected program names and continue to the faculty source." link="/faculties" /><StepCard number="03" title="Confirm officially" body="Use the official NBU homepage for current registration and scholarship access." href="https://northbkk.ac.th/" /></div></section><section className="bg-amber-300 py-16"><div className="page-width grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="eyebrow text-amber-950">Scholarships & student-loan fund</p><h2 className="font-display text-4xl font-semibold text-emerald-950 sm:text-5xl">Verified labels. Current details live elsewhere.</h2><p className="mt-4 max-w-2xl text-amber-950/80">The official homepage exposes scholarship and student-loan-fund entry points. This mockup intentionally avoids duplicating eligibility or deadline claims.</p></div><a className="rounded-full bg-emerald-950 px-6 py-3.5 text-center font-bold text-white" href="https://northbkk.ac.th/" target="_blank" rel="noreferrer">Visit official homepage ↗</a></div></section></main> }
function StepCard({ number, title, body, link, href }: { number: string; title: string; body: string; link?: string; href?: string }) { const content = <><span className="font-display text-6xl text-emerald-200">{number}</span><h3 className="mt-10 font-display text-2xl font-semibold">{title}</h3><p className="mt-3 text-slate-600">{body}</p><span className="mt-8 inline-flex items-center gap-2 font-bold text-emerald-800">Continue <ChevronRight size={17} /></span></>; return href ? <a href={href} target="_blank" rel="noreferrer" className="rounded-[2rem] border border-slate-200 bg-white p-7 transition hover:shadow-lg">{content}</a> : <Link to={link!} className="rounded-[2rem] border border-slate-200 bg-white p-7 transition hover:shadow-lg">{content}</Link> }
function ServicesPage() { return <main><PageHero eyebrow="Student services" title="The right tool, without the runaround." body="Quick links to verified services. Account-specific actions remain on official external systems and are not reproduced here." /><section className="page-width py-20 sm:py-28"><div className="mb-10 rounded-2xl border border-sky-200 bg-sky-50 p-5 text-sm leading-6 text-sky-950"><strong>Availability note:</strong> the official <code>student.php</code> page returned HTTP 403 to the public crawler on 8 October 2026. This mockup does not infer its contents or present a student dashboard.</div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{serviceItems.map((service) => <ServiceCard key={service.name} service={service} />)}</div></section></main> }
function Callout() { return <section className="page-width pb-20 sm:pb-28"><div className="relative overflow-hidden rounded-[2.5rem] bg-amber-300 px-7 py-12 sm:px-14 sm:py-16"><div className="absolute -right-20 -top-24 size-64 rounded-full border-[45px] border-amber-200" /><div className="relative grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="eyebrow text-amber-950">Ready to explore?</p><h2 className="max-w-2xl font-display text-4xl font-semibold leading-tight text-emerald-950 sm:text-5xl">Find the program page that fits your next move.</h2><p className="mt-4 text-amber-950/80">Mock interface copy. Confirm all current admissions information with NBU.</p></div><Link to="/programs" className="rounded-full bg-emerald-950 px-6 py-3.5 text-center font-bold text-white">Browse programs</Link></div></div></section> }
function Footer() { const contacts = [['Saphan Mai campus', '0-2972-7200'], ['Rangsit campus', '0-2533-1000'], ['Nonthaburi education centre', '0-2589-1133 ext. 534']]; return <footer className="bg-emerald-950 text-white"><div className="page-width py-14"><div className="grid gap-10 lg:grid-cols-[1.2fr_.8fr_1fr]"><div><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-full bg-amber-300 text-emerald-950"><GraduationCap /></span><span className="font-display text-2xl font-semibold">North Bangkok University</span></div><p className="mt-5 max-w-md text-sm leading-6 text-emerald-200">An independent, unofficial interface concept. No official university logos, photographs, or authenticated functionality are reproduced.</p></div><div><h3 className="text-xs font-bold uppercase tracking-[.2em] text-amber-300">Explore</h3><div className="mt-5 grid gap-3 text-sm">{primaryNavigation.slice(1).map((item) => <Link key={item.to} to={item.to} className="text-emerald-100 hover:text-white">{item.label}</Link>)}</div></div><div><h3 className="text-xs font-bold uppercase tracking-[.2em] text-amber-300">Verified public contacts</h3><div className="mt-5 grid gap-4">{contacts.map(([label, phone]) => <div key={label} className="flex gap-3"><Phone size={16} className="mt-1 shrink-0 text-emerald-300" /><div><p className="text-sm font-semibold">{label}</p><p className="text-sm text-emerald-200">{phone}</p></div></div>)}</div></div></div><div className="mt-12 flex flex-col justify-between gap-4 border-t border-white/10 pt-6 text-xs text-emerald-300 sm:flex-row"><p>Unofficial design mockup · Research checked 8 October 2026</p><a href="https://northbkk.ac.th/" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 font-bold text-white"><MapPin size={14} /> Official NBU website <ExternalLink size={13} /></a></div></div></footer> }

export default function App() { return <AppShell><Routes><Route path="/" element={<HomePage />} /><Route path="/faculties" element={<FacultiesPage />} /><Route path="/programs" element={<ProgramsPage />} /><Route path="/news" element={<NewsPage />} /><Route path="/admissions" element={<AdmissionsPage />} /><Route path="/student-services" element={<ServicesPage />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></AppShell> }
